name: path_pilot
description: "Create, upload, and analyze precise path instructions for line-following robots."
repository: https://github.com/Cupcake-Systems/path_pilot
issue_tracker: https://github.com/Cupcake-Systems/path_pilot/issues

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  file_picker: ^9.0.0
  path: ^1.9.0
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  flutter_resizable_container: ^3.0.3
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  filesystem_picker: ^4.1.0
  flex_color_picker: ^3.6.0
  flutter_expandable_fab: ^2.3.0
  intl: ^0.20.0
  path_provider: ^2.1.5
  grouped_list: ^6.0.0
  http: ^1.2.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.webp"
  android: true
  min_sdk_android: 21
  adaptive_icon_background: "#46475a"
  adaptive_icon_foreground: "assets/icon/app_icon.webp"
  windows:
    image_path: "assets/icon/windows_icon.webp"
    generate: true
    icon_size: 256

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

  assets:
    - assets/robi_illustration.webp
    - assets/robi_illustration_bottom_labeled.webp
    - assets/repo_banner.webp
